//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVCon
    {
        public int ID { get; set; }
        public string TenCV { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> ThgianBD { get; set; }
        public Nullable<System.DateTime> ThgianKT { get; set; }
        public string NguoiTH { get; set; }
        public string NguoiGiao { get; set; }
        public Nullable<int> CvChaID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual CVCha CVCha { get; set; }
    }
}
